name: Multi-Language DSA CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_c:
    name: Build & Test C
    runs-on: macos-latest
    continue-on-error: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Inst
